FROM mcr.microsoft.com/playwright:v1.57.0-noble

WORKDIR /app

RUN apt-get update && apt-get install -y unzip \
    && rm -rf /var/lib/apt/lists/*

RUN corepack enable && corepack prepare pnpm@10.32.1 --activate

COPY package.json pnpm-workspace.yaml pnpm-lock.yaml /app/
COPY frontend/package.json /app/frontend/

WORKDIR /app
RUN pnpm install --frozen-lockfile

COPY ./frontend /app/frontend

ARG VITE_API_URL
